drop table if exists sensors cascade;
drop table if exists measurements cascade;

CREATE TABLE IF NOT EXISTS sensors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(254)                NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS measurements
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value      DECIMAL                     NOT NULL,
    raining    BOOLEAN                     NOT NULL,
    sensor_id  BIGINT REFERENCES sensors (id) ON DELETE CASCADE,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL
);